version: 2

# =======================
# 1. Build Binary Section
# =======================
builds:
  - id: server
    main: ./cmd/server
    binary: go-api-starter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/novrirahman-space/go-api-starter/internal/version.Version={{.Version}}
      - -X github.com/novrirahman-space/go-api-starter/internal/version.Commit={{.Commit}}
      - -X github.com/novrirahman-space/go-api-starter/internal/version.BuildDate={{.Date}}

# ===========================
# 2. Docker Image Build Rules
# ===========================
dockers:
  # --- AMD64 Image ---
  - ids: [server]
    dockerfile: Dockerfile.goreleaser
    use: buildx
    image_templates:
      - ghcr.io/novrirahman-space/go-api-starter:{{ .Version }}-amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--push"

  # --- ARM64 Image ---
  - ids: [server]
    dockerfile: Dockerfile.goreleaser
    use: buildx
    image_templates:
      - ghcr.io/novrirahman-space/go-api-starter:{{ .Version }}-arm64
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--push"

# ===========================
# 3. Multi-Arch Manifest List
# ===========================
docker_manifests:
  - name_template: ghcr.io/novrirahman-space/go-api-starter:{{ .Version }}
    image_templates:
      - ghcr.io/novrirahman-space/go-api-starter:{{ .Version }}-amd64
      - ghcr.io/novrirahman-space/go-api-starter:{{ .Version }}-arm64
  - name_template: ghcr.io/novrirahman-space/go-api-starter:latest
    image_templates:
      - ghcr.io/novrirahman-space/go-api-starter:{{ .Version }}-amd64
      - ghcr.io/novrirahman-space/go-api-starter:{{ .Version }}-arm64

# ===========================
# 4. Release Configuration
# ===========================
release:
  github:
    owner: novrirahman-space
    name: go-api-starter
