version: 2

builds:
  - id: server
    main: ./cmd/server
    binary: go-api-starter
    env: [CGO_ENABLED=0]
    # Boleh build semua OS untuk release binaries...
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

dockers:
  - ids: [server]  # gunakan binary dari build "server"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    push: true # push multi-arch image
    image_templates:
      - ghcr.io/novrirahman-space/go-api-starter:{{ .Tag }}
      - ghcr.io/novrirahman-space/go-api-starter:latest
    # build multi-arch
    build_flag_templates:
      - "--platform=linux/amd64,linux/arm64"

release:
  github:
    owner: novrirahman-space
    name: go-api-starter
